spring:
  application:
    name: graphql
  datasource:
    url: jdbc:h2:mem:graphql
    driverClassName: org.h2.Driver
    username: root
    password:
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  graphql:
    graphiql:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
#        ddl-auto: create
        format_sql: true